INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (1, '1', 1);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (2, '1', 3);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (3, '1', 6);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (4, '1', 7);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (5, '2', 1);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (6, '2', 2);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (8, '2', 3);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (9, '2', 4);
INSERT INTO `sys_role_menu` (`id`, `role_id`, `menu_id`) VALUES (10, '2', 5);
